- name: check warden configuration
  stat:
    path: "/opt/warden_client/warden_filer.cfg"
  register: was_configured

- name: Install Warden
  block:
  - name: Create warden directory
    file:
      path: "/opt/warden_client/"
      state: directory
      mode: 0755

  - name: Copy Warden 3.X
    copy:
      src: "{{ item }}"
      dest: /tmp/
    with_items:
      - warden_client_3.0-beta2.tar.bz2
      - contrib_3.0-beta2.tar.bz2

  - name: Unarchive Warden 3.X
    unarchive:
      src: "/tmp/{{ item }}"
      dest: "/tmp/"
      remote_src: yes
    with_items:
      - warden_client_3.0-beta2.tar.bz2
      - contrib_3.0-beta2.tar.bz2

  - name: Copy warden source files
    copy:
      src: "/tmp/{{ item }}"
      dest: "/opt/warden_client/"
      remote_src: yes
    with_items:
      - warden_client_3.0-beta2/warden_client.py
      - contrib_3.0-beta2/warden_filer/warden_filer_receiver
      - contrib_3.0-beta2/warden_filer/warden_filer_sender
      - contrib_3.0-beta2/warden_filer/warden_filer.py

  - name: Configure warden_filer_receiver
    lineinfile:
      dest: "/opt/warden_client/warden_filer_receiver"
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    with_items:
      - { regexp: '^DAEMON_PATH', line: 'DAEMON_PATH=/opt/warden_client/"$DAEMON_NAME".py' }
      - { regexp: '^CONFIG', line: 'CONFIG=/opt/warden_client/"$DAEMON_NAME".cfg' }

  - name: Changing perm of warden_filer_receiver, adding +x
    file:
      dest: "{{ item }}"
      mode: "+x"
    with_items:
      - "/opt/warden_client/warden_filer_receiver"
      - "/opt/warden_client/warden_filer.py"

  - name: Specify python version
    lineinfile:
      path: "/opt/warden_client/warden_filer.py"
      regexp: '^#!/usr/bin/python$'
      line: '#!/usr/bin/python2'

  - name: Copy warden config files
    copy:
      src: "{{ item }}"
      dest: "/opt/warden_client/"
      force: yes
    with_items:
      - warden_client.cfg
      - warden_filer.cfg

  - name: Copy warden keys
    ignore_errors: yes
    copy:
      src: "{{ item }}"
      dest: "/opt/warden_client/"
    with_items:
      - "{{ warden_ca_path }}"
      - "{{ warden_cert_path }}"
      - "{{ warden_key_path }}"
  when: was_configured.stat.exists == False
