---
- hosts: all
  vars:
    # Dashboard folder
    graphqlapi_folder: /home/vagrant/graphqlapi
    neo4j_bolt_url: "bolt://localhost:7687"
    neo4j_username: "neo4j"
    neo4j_password: "password"
    # Port
    port: 4001
  environment:
    GRAPHQL_SERVER_PORT: "{{ port }}"
  roles:
    - graphqlapi
