services:
  neo4j:
    image: neo4j:4.4.32
    restart: unless-stopped
    hostname: neo4j
    container_name: neo4j
    volumes:
        - /$HOME/neo4j/data:/data
        - /$HOME/Documentos/CRUSOE/datasets:/dumps
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/pleaseletmein
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_dbms_memory_heap_initial__size=1G
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_memory_pagecache_size=1G
